#Week3

1- Pandas

2- Numpy

3- API 

1- Panads

In [3]:
#1 Import the Pandas Library
import pandas as pd

x = {'Name': ['Mayar','Khaled','Lamees', 'Hassan'], 
     'ID': [1, 2, 3, 4],
     'Department': ['Architect Group', 'Software Group', 'Design Team', 'Infrastructure'], 
     'Salary':[100000, 80000, 50000, 60000]}

#casting the dictionary to a DataFrame
df = pd.DataFrame(x)
df

Name  ID       Department  Salary
0   Mayar   1  Architect Group  100000
1  Khaled   2   Software Group   80000
2  Lamees   3      Design Team   50000
3  Hassan   4   Infrastructure   60000

Panads Load Data:

In [5]:
#2 # Import required library

import pandas as pd
# Read data from CSV file

csv_path = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%204/data/TopSellingAlbums.csv'
df = pd.read_csv(csv_path)
df.head()


Artist                      Album  Released   Length  \
0  Michael Jackson                   Thriller      1982  0:42:19   
1            AC/DC              Back in Black      1980  0:42:11   
2       Pink Floyd  The Dark Side of the Moon      1973  0:42:49   
3  Whitney Houston              The Bodyguard      1992  0:57:44   
4        Meat Loaf            Bat Out of Hell      1977  0:46:33   

                         Genre  Music Recording Sales (millions)  \
0               pop, rock, R&B                              46.0   
1                    hard rock                              26.1   
2             progressive rock                              24.2   
3               R&B, soul, pop                              27.4   
4  hard rock, progressive rock                              20.6   

   Claimed Sales (millions) Released.1 Soundtrack  Rating  
0                        65  30-Nov-82        NaN    10.0  
1                        50  25-Jul-80        NaN     9.5  
2                        45  01-Mar-73        NaN     9.0  
3                        44  17-Nov-92          Y     8.5  
4                        43  21-Oct-77        NaN     8.0

2- 1D Numpy:

In [8]:
#Import numpy library

import numpy as np 
# Create a numpy array
m = np.array([0, 1, 2, 3, 4])
m

#Check the type of the array
type(m)

numpy.ndarray

2- 2D Numpy:

In [11]:
# Import the libraries

import numpy as np 
import matplotlib.pyplot as plt

a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [12]:
# Show the numpy array dimensions
A.ndim

2

In [13]:
# Access the element on the first and second rows and third column

A[0:2, 2]

array([13, 23])

BASIC OPERATIONS IN NUMPY:

In [14]:
# Create a numpy array X
X = np.array([[1, 0], [0, 1]]) 
X

# Create a numpy array Y
Y = np.array([[2, 1], [1, 2]]) 
Y

# Add X and Y
Z = X + Y
Z

array([[3, 1],
       [1, 3]])

3- API (Applications Programming Interface):

Pandas is an API:

In [17]:
import pandas as pd
import matplotlib.pyplot as plt

dict_={'a':[11,21,31],'b':[12,22,32]}
df=pd.DataFrame(dict_)
type(df)
df.head()
df.mean()


a    21.0
b    22.0
dtype: float64

REST APIs:

In [18]:
!pip install nba_api
from nba_api.stats.static import teams
import matplotlib.pyplot as plt

#https://pypi.org/project/nba-api/
nba_teams = teams.get_teams()
nba_teams[0:3]
dict_nba_team=one_dict(nba_teams)
df_teams=pd.DataFrame(dict_nba_team)
df_teams.head()

     -------------------------------------- 257.2/257.2 kB 1.2 MB/s eta 0:00:00


id             full_name abbreviation   nickname         city  \
0  1610612737         Atlanta Hawks          ATL      Hawks      Atlanta   
1  1610612738        Boston Celtics          BOS    Celtics       Boston   
2  1610612739   Cleveland Cavaliers          CLE  Cavaliers    Cleveland   
3  1610612740  New Orleans Pelicans          NOP   Pelicans  New Orleans   
4  1610612741         Chicago Bulls          CHI      Bulls      Chicago   

           state  year_founded  
0        Georgia          1949  
1  Massachusetts          1946  
2           Ohio          1970  
3      Louisiana          2002  
4       Illinois          1966